name: CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Perform:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize
        uses: github/codeql-action/init@v1
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Analysis
        uses: github/codeql-action/analyze@v1
